### ISSUE TITLE
mintclub.network("sepolia").token('SuperSquad').create({...values}) request change network with wrong network currency ticker.

### ISSUE THREAD

**Issue by Resister-boy** [Steemhunt/mint.club-v2-sdk#2]
mintclub.network("sepolia").token('SuperSquad').create({...values}) request change network with wrong network currency ticker. I seems request currency ticker "SEP" while sepolia currency ticker is "Sepolia ETH". So my metamask can not notice.

![image](https://github.com/Steemhunt/mint.club-v2-sdk/assets/104838360/c4d8acce-ea1f-49b3-940c-1828426f7a03)

![image](https://github.com/Steemhunt/mint.club-v2-sdk/assets/104838360/8ea35113-359f-4dde-84fd-11d6f40a6596)

**Comment by ggomaeng** [comment]
@Resister-boy you can safely ignore this warning. It doesn't affect the usage - it's marked as SEP to indicate that it's testnet.

This chain information from [Viem](https://github.com/wevm/viem/blob/main/src/chains/definitions/sepolia.ts).
